package tests

import app ".."
import "core:log"
import "core:testing"
import "../gfx"

// A cut of the real Aether colors.toml Omarchy v4 writes: the semantic palette, a comment
// line, a section-less flat body, and a `mode` key whose value is not a colour.
AETHER :: `# Generated by Aether for Omarchy v4.
mode = "dark"

accent = "#9253be"
selection = "#d4be98"
muted = "#46413e"

background = "#32302f"
dark_background = "#262423"
lighter_background = "#474544"

foreground = "#d4be98"
dark_foreground = "#9f8f72"
bright_foreground = "#dfceb2"

red = "#ea6962"
yellow = "#d8a657"
orange = "#ed807a"
green = "#a9b665"
cyan = "#89b482"
magenta = "#d3869b"

bright_red = "#ea6962"
`

// A theme written before the semantic palette: ANSI names only, nothing else.
LEGACY :: `color0 = "#1d2021"
color1 = "#cc241d"
color2 = "#98971a"
color3 = "#d79921"
color5 = "#b16286"
color6 = "#689d6a"
color7 = "#ebdbb2"
color8 = "#928374"
`

@(private = "file")
hex :: proc(c: [3]f32) -> u32 {
    return (u32(c.r * 255 + 0.5) << 16) | (u32(c.g * 255 + 0.5) << 8) | u32(c.b * 255 + 0.5)
}

// The straight one-to-one keys. These must come through as the palette wrote them, with no
// blending: a theme's accent IS Slopd's accent.
@(test)
test_omarchy_maps_palette :: proc(t: ^testing.T) {
    th, ok := gfx.omarchy_theme_from_src(AETHER)
    testing.expect(t, ok, "a semantic palette must load")

    testing.expect_value(t, hex(th.bg), 0x32302f)
    testing.expect_value(t, hex(th.fg), 0xd4be98)
    testing.expect_value(t, hex(th.accent), 0x9253be)
    testing.expect_value(t, hex(th.urgent), 0xea6962)
    testing.expect_value(t, hex(th.border_light), 0x474544) // lighter_background, not a blend
    testing.expect_value(t, hex(th.border_dark), 0x262423) // dark_background

    testing.expect_value(t, hex(th.code_keyword), 0xd3869b) // magenta
    testing.expect_value(t, hex(th.code_string), 0xd8a657) // yellow
    testing.expect_value(t, hex(th.code_type), 0xa9b665) // green
    testing.expect_value(t, hex(th.code_return_type), 0x89b482) // cyan
    testing.expect_value(t, hex(th.code_operator), 0xed807a) // orange
    testing.expect_value(t, hex(th.code_variable), 0xd4be98) // foreground
}

// muted must NOT take Omarchy's `muted` key. That key is a background-weight fill; Slopd's
// muted is body text. Aether sets muted #46413e and dark_foreground #9f8f72 — taking the
// wrong one makes every comment and every unfocused label unreadable against bg.
@(test)
test_omarchy_muted_is_text_not_fill :: proc(t: ^testing.T) {
    th, _ := gfx.omarchy_theme_from_src(AETHER)
    testing.expect_value(t, hex(th.muted), 0x9f8f72) // dark_foreground
    testing.expect_value(t, hex(th.code_comment), 0x9f8f72)
}

// A staged command line has to out-shout `urgent`. Aether sets bright_red EQUAL to red, so a
// straight read would flatten the two into one colour and the alert would stop reading as one.
@(test)
test_omarchy_cl_inject_beats_urgent :: proc(t: ^testing.T) {
    th, _ := gfx.omarchy_theme_from_src(AETHER)
    testing.expect(t, hex(th.cl_inject) != hex(th.urgent), "cl_inject must differ from urgent")
    testing.expect(t, th.cl_inject.r > th.urgent.r, "and must be the redder of the two")
    testing.expect(t, th.cl_inject.g < th.urgent.g)
}

// Keys no palette carries are blends off bg. Each one must land BETWEEN bg and its target,
// or the guides and the selection either vanish into the background or cover the code.
@(test)
test_omarchy_derives_guides :: proc(t: ^testing.T) {
    th, _ := gfx.omarchy_theme_from_src(AETHER)

    Derived :: struct {
        name: string,
        col:  [3]f32,
    }
    derived := []Derived {
        {"separator", th.separator},
        {"selection", th.selection},
        {"line_highlight", th.line_highlight},
        {"whitespace", th.whitespace},
        {"indent_guide", th.indent_guide},
    }
    for d in derived {
        testing.expectf(t, d.col.r > th.bg.r, "%s must lift off bg", d.name)
        testing.expectf(t, d.col.r < th.fg.r, "%s must stay under fg", d.name)
    }

    // The active rail carries the accent, so it is checked against the accent, not fg.
    testing.expect(t, th.indent_guide_active.b > th.indent_guide.b)
    testing.expect(t, th.indent_guide_active.b < th.accent.b)
}

// A theme with only color0..color15 still has to produce a usable palette, because that is
// what Omarchy's own cascade does with one. Nothing may fall back to the baked-in gruvbox.
@(test)
test_omarchy_legacy_ansi_palette :: proc(t: ^testing.T) {
    th, ok := gfx.omarchy_theme_from_src(LEGACY)
    testing.expect(t, ok, "an ANSI-only palette must load")

    testing.expect_value(t, hex(th.bg), 0x1d2021) // color0
    testing.expect_value(t, hex(th.fg), 0xebdbb2) // color7
    testing.expect_value(t, hex(th.muted), 0x928374) // color8
    testing.expect_value(t, hex(th.accent), 0xb16286) // no accent key -> color5
    testing.expect_value(t, hex(th.urgent), 0xcc241d) // color1
    testing.expect_value(t, hex(th.code_return_type), 0x689d6a) // color6

    // color4 is absent from this file, and orange is absent from every ANSI palette. Both
    // must land on a real colour rather than a hole.
    testing.expect_value(t, hex(th.code_operator), 0xd79921) // orange falls back to yellow
}

// Nothing parseable means the caller keeps its own default. A colours.toml that is missing,
// truncated mid-write by a theme switch, or full of rgba() must never yield a black theme.
@(test)
test_omarchy_rejects_empty_source :: proc(t: ^testing.T) {
    def := gfx.default_theme()

    empty := []string{"", "# only a comment\n", "mode = \"dark\"\n", "accent = rgba(11223344)\n"}
    for src in empty {
        th, ok := gfx.omarchy_theme_from_src(src)
        testing.expect(t, !ok, "a palette with no colour must report failure")
        testing.expect_value(t, hex(th.bg), hex(def.bg))
        testing.expect_value(t, hex(th.accent), hex(def.accent))
    }
}

// The token is reserved. theme_resolve must refuse it so a themes/omarchy.theme file can
// never shadow the live desktop palette that theme_load reads first.
@(test)
test_omarchy_token_is_reserved :: proc(t: ^testing.T) {
    testing.expect_value(t, app.theme_resolve(gfx.OMARCHY_THEME), "")
}

// The synthetic palettes above pin the mapping; this one pins the PATH and the real file
// format. It runs only on a machine that has a theme applied, because CI has none.
@(test)
test_omarchy_reads_live_palette :: proc(t: ^testing.T) {
    if !gfx.omarchy_available() {
        log.info("[skip] no Omarchy theme applied; see theme_omarchy.odin header")
        return
    }
    th, ok := gfx.omarchy_theme(gfx.omarchy_colors_file(context.temp_allocator))
    testing.expect(t, ok, "the live colors.toml must parse")

    // The palette is real, so the only claim worth making is that it is not the baked-in
    // one and not black: the desktop's own colours actually landed.
    def := gfx.default_theme()
    testing.expect(t, hex(th.bg) != hex(def.bg) || hex(th.accent) != hex(def.accent))
    testing.expect(t, hex(th.fg) != hex(th.bg), "fg must not collapse into bg")
    log.infof("live palette: bg #%06x fg #%06x accent #%06x", hex(th.bg), hex(th.fg), hex(th.accent))
}
