package main

import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:slice"
import "core:strings"

// Grammar management, shared by the Config pane and the `--health` / `--grammar` CLI flags.
// Grammars are not shipped: a language is installed at runtime, which keeps the dist tiny. Each
// is a compiled grammars/<lang>.so plus the grammar's own highlights query grammars/<lang>.scm.
// grammars/ is a data folder (install.odin), created on demand. The `languages` registry itself
// is baked into the binary — see load_grammars.

// Name, source repo, pinned rev, an optional subpath (for multi-grammar repos), and the
// extensions that select it. Loaded from the generated `languages` file.
Grammar :: struct {
    name:    string, // owned
    repo:    string, // owned
    rev:     string, // owned; "" tracks the default branch
    subpath: string, // owned; "" means the grammar is at the repo root
    exts:    []string, // owned; no leading dot
}

// A data folder, so install.odin decides where it sits. Returned existing or not: the first
// install creates it. The caller owns the result.
grammars_dir :: proc(allocator := context.allocator) -> string {
    return data_asset("grammars", allocator)
}

// The caller owns the result.
grammar_lib_path :: proc(dir, lang: string, allocator := context.allocator) -> string {
    lib := fmt.tprintf("%s.so", lang)
    return filepath.join({dir, lib}, allocator) or_else strings.clone(lib, allocator)
}

// The installed highlights query. The caller owns the result.
grammar_query_path :: proc(dir, lang: string, allocator := context.allocator) -> string {
    scm := fmt.tprintf("%s.scm", lang)
    return filepath.join({dir, scm}, allocator) or_else strings.clone(scm, allocator)
}

grammar_present :: proc(dir, lang: string) -> bool {
    return os.exists(grammar_lib_path(dir, lang, context.temp_allocator))
}

// --- the language registry (generated `languages` file) ---

// Baked in, so the release is the binary. Generated by tools/gen-languages.py and COMMITTED,
// because #load resolves at compile time and a fresh clone must still build.
LANGUAGES_SRC := string(#load("../languages"))

// Tab-separated, '-' for empty fields:
//   name <TAB> repo <TAB> rev <TAB> subpath <TAB> ext,ext,...
// Owned by context.allocator; free with grammars_destroy under the same context.
load_grammars :: proc() -> []Grammar {
    out := make([dynamic]Grammar, 0, 256)
    rest := LANGUAGES_SRC
    for line in strings.split_lines_iterator(&rest) {
        s := strings.trim_space(line)
        if len(s) == 0 || s[0] == '#' {
            continue
        }
        f := strings.split(s, "\t", context.temp_allocator)
        if len(f) < 2 {
            continue
        }
        g := Grammar {
            name = strings.clone(f[0]),
            repo = strings.clone(f[1]),
        }
        if len(f) > 2 && f[2] != "-" {
            g.rev = strings.clone(f[2])
        }
        if len(f) > 3 && f[3] != "-" {
            g.subpath = strings.clone(f[3])
        }
        if len(f) > 4 && f[4] != "-" {
            parts := strings.split(f[4], ",", context.temp_allocator)
            exts := make([]string, len(parts))
            for p, i in parts {
                exts[i] = strings.clone(strings.trim_space(p))
            }
            g.exts = exts
        }
        append(&out, g)
    }
    // Cloned to an exact length: grammars_destroy frees with `delete`, which sizes by len,
    // while a dynamic array's backing is its cap.
    defer delete(out)
    return slice.clone(out[:])
}

grammars_destroy :: proc(grammars: []Grammar) {
    for g in grammars {
        delete(g.name)
        delete(g.repo)
        delete(g.rev)
        delete(g.subpath)
        for e in g.exts {
            delete(e)
        }
        delete(g.exts)
    }
    delete(grammars)
}

grammar_find :: proc(grammars: []Grammar, name: string) -> (^Grammar, bool) {
    for &g in grammars {
        if g.name == name {
            return &g, true
        }
    }
    return nil, false
}

// Built once at load: the lookup runs on every editor paint and modeline, over 300 languages
// and 700 extensions. First entry wins, as the linear scan did. Keys and values BORROW the
// registry's strings, so this must not outlive it.
grammar_ext_index :: proc(grammars: []Grammar) -> map[string]string {
    index := make(map[string]string)
    for g in grammars {
        for e in g.exts {
            if e not_in index {
                index[e] = g.name
            }
        }
    }
    return index
}

// No leading dot. Picks a buffer's grammar for highlighting.
grammar_for_ext :: proc(index: map[string]string, ext: string) -> (name: string, ok: bool) {
    if ext == "" {
        return "", false
    }
    name, ok = index[ext]
    return
}

// --- install actions (msg is temp-allocated, for printing / surfacing) ---

// Captures combined stdout+stderr, temp-allocated. ok iff it exited 0.
@(private = "file")
run :: proc(args: []string, working_dir := "") -> (ok: bool, out: string) {
    state, sout, serr, err := os.process_exec(
        os.Process_Desc{command = args, working_dir = working_dir},
        context.temp_allocator,
    )
    if err != nil {
        return false, fmt.tprintf("exec error: %v", err)
    }
    return state.exited && state.exit_code == 0, fmt.tprintf("%s%s", string(sout), string(serr))
}

// Fetch and build into grammars/<lang>.so, and copy its highlights.scm alongside. Tracks the
// registry's pinned rev, honouring its subpath.
grammar_install :: proc(dir: string, g: Grammar) -> (ok: bool, msg: string) {
    if g.repo == "" {
        return false, fmt.tprintf("%s: no grammar source in the registry", g.name)
    }
    if !os.exists(dir) {
        if err := os.make_directory(dir); err != nil {
            return false, fmt.tprintf("%s: cannot create %s (%v)", g.name, dir, err)
        }
    }

    // Clone and compile in a temp dir, then publish atomically by renaming staged files within
    // grammars/ — same filesystem, so a failed build cannot clobber a working install.
    tmp := os.get_env("TMPDIR", context.temp_allocator)
    if tmp == "" {
        tmp = "/tmp"
    }
    build := filepath.join({tmp, fmt.tprintf("slopd-grammar-%s", g.name)}, context.temp_allocator) or_else ""
    run({"rm", "-rf", build}) // clear any stale build dir
    defer run({"rm", "-rf", build})

    so := grammar_lib_path(dir, g.name, context.temp_allocator)
    scm := grammar_query_path(dir, g.name, context.temp_allocator)
    so_stage := fmt.tprintf("%s.tmp", so)
    scm_stage := fmt.tprintf("%s.tmp", scm)
    defer {
        _ = os.remove(so_stage) // a no-op once renamed into place
        _ = os.remove(scm_stage)
    }

    // Shallow-fetch the pinned rev; with no rev, clone the default branch.
    if g.rev != "" {
        if err := os.make_directory(build); err != nil {
            return false, fmt.tprintf("%s: cannot create build dir (%v)", g.name, err)
        }
        steps := [][]string {
            {"git", "init", "-q"},
            {"git", "remote", "add", "origin", g.repo},
            {"git", "fetch", "-q", "--depth", "1", "origin", g.rev},
            {"git", "checkout", "-q", "FETCH_HEAD"},
        }
        for step in steps {
            if sok, sout := run(step, build); !sok {
                return false, fmt.tprintf("%s: `%s` failed\n%s", g.name, strings.join(step, " ", context.temp_allocator), sout)
            }
        }
    } else if cok, cout := run({"git", "clone", "-q", "--depth", "1", g.repo, build}); !cok {
        return false, fmt.tprintf("%s: git clone failed\n%s", g.name, cout)
    }

    // Honouring subpath, for multi-grammar repos.
    root := build
    if g.subpath != "" {
        root = filepath.join({build, g.subpath}, context.temp_allocator) or_else build
    }
    src := filepath.join({root, "src"}, context.temp_allocator) or_else ""
    parser := filepath.join({src, "parser.c"}, context.temp_allocator) or_else ""
    if !os.exists(parser) {
        return false, fmt.tprintf("%s: no src/parser.c (looked in %s)", g.name, src)
    }

    // Compile to the staging lib, then swap it into place.
    if cok, cout := compile_grammar(src, parser, build, so_stage); !cok {
        return false, fmt.tprintf("%s: compile failed\n%s", g.name, cout)
    }
    if err := os.rename(so_stage, so); err != nil {
        return false, fmt.tprintf("%s: publish failed (%v)", g.name, err)
    }

    // If the repo ships one. A missing query is surfaced: the grammar parses but does not
    // colour, and there is no other signal.
    has_query := install_query(root, build, scm_stage) && os.rename(scm_stage, scm) == nil
    if !has_query {
        return true, fmt.tprintf("%s: installed (no highlights query in repo — parses, won't colour)", g.name)
    }
    return true, fmt.tprintf("%s: installed", g.name)
}

// parser.c plus an optional external scanner. A C scanner links in one `cc -shared`; a C++ one
// is compiled separately and linked with c++.
@(private = "file")
compile_grammar :: proc(src, parser, build, dest: string) -> (ok: bool, out: string) {
    inc := fmt.tprintf("-I%s", src)
    scanner_c := filepath.join({src, "scanner.c"}, context.temp_allocator) or_else ""
    scanner_cc := filepath.join({src, "scanner.cc"}, context.temp_allocator) or_else ""

    if os.exists(scanner_cc) {
        po := filepath.join({build, "parser.o"}, context.temp_allocator) or_else ""
        sco := filepath.join({build, "scanner.o"}, context.temp_allocator) or_else ""
        if cok, cout := run({"cc", "-c", "-O2", "-fPIC", inc, parser, "-o", po}); !cok {
            return false, cout
        }
        if cok, cout := run({"c++", "-c", "-O2", "-fPIC", inc, scanner_cc, "-o", sco}); !cok {
            return false, cout
        }
        return run({"c++", "-shared", po, sco, "-o", dest})
    }

    args := make([dynamic]string, 0, 8, context.temp_allocator)
    append(&args, "cc", "-shared", "-O2", "-fPIC", inc, parser)
    if os.exists(scanner_c) {
        append(&args, scanner_c)
    }
    append(&args, "-o", dest)
    return run(args[:])
}

// The grammar root first, then the repo root for subpath grammars. True only if a query was
// found AND written; the caller surfaces a missing one.
@(private = "file")
install_query :: proc(root, build, dest: string) -> (found: bool) {
    candidates := [?]string {
        filepath.join({root, "queries", "highlights.scm"}, context.temp_allocator) or_else "",
        filepath.join({build, "queries", "highlights.scm"}, context.temp_allocator) or_else "",
    }
    for c in candidates {
        if c == "" || !os.exists(c) {
            continue
        }
        data := os.read_entire_file_from_path(c, context.temp_allocator) or_else nil
        if data == nil {
            continue
        }
        return os.write_entire_file(dest, data) == nil
    }
    return false
}

// An idempotent reinstall, which picks up a registry refresh that bumped the rev.
grammar_update :: proc(dir: string, g: Grammar) -> (ok: bool, msg: string) {
    return grammar_install(dir, g)
}

// Its compiled lib and the highlights query.
grammar_uninstall :: proc(dir, lang: string) -> (ok: bool, msg: string) {
    lib := grammar_lib_path(dir, lang, context.temp_allocator)
    if !os.exists(lib) {
        return false, fmt.tprintf("%s: not installed", lang)
    }
    if err := os.remove(lib); err != nil {
        return false, fmt.tprintf("%s: remove failed (%v)", lang, err)
    }
    if scm := grammar_query_path(dir, lang, context.temp_allocator); os.exists(scm) {
        _ = os.remove(scm)
    }
    return true, fmt.tprintf("%s: uninstalled", lang)
}

// --- CLI (`slopd --health [lang]`, `slopd --grammar <action> <lang>`) ---

// Before the GLFW window opens. True if a command was handled, so the caller exits.
grammar_cli :: proc(args: []string) -> (handled: bool) {
    for i := 0; i < len(args); i += 1 {
        switch args[i] {
        case "--health":
            lang := i + 1 < len(args) ? args[i + 1] : ""
            grammar_print_health(lang)
            return true
        case "--grammar":
            if i + 2 >= len(args) {
                fmt.eprintln("usage: slopd --grammar install|uninstall|update <lang>")
                return true
            }
            grammar_run_action(args[i + 1], args[i + 2])
            return true
        }
    }
    return false
}

@(private = "file")
grammar_run_action :: proc(action, lang: string) {
    dir := grammars_dir(context.temp_allocator)
    grammars := load_grammars()
    defer grammars_destroy(grammars)
    msg: string
    switch action {
    case "install", "update":
        g, found := grammar_find(grammars, lang)
        if !found {
            msg = fmt.tprintf("%s: unknown language (not in the registry)", lang)
        } else if action == "install" {
            _, msg = grammar_install(dir, g^)
        } else {
            _, msg = grammar_update(dir, g^)
        }
    case "uninstall":
        _, msg = grammar_uninstall(dir, lang)
    case:
        fmt.eprintfln("unknown grammar action: %s (want install|uninstall|update)", action)
        return
    }
    fmt.println(msg)
}

// One language, or a ✓/✗ table for the whole registry.
grammar_print_health :: proc(lang: string) {
    dir := grammars_dir(context.temp_allocator)
    grammars := load_grammars()
    defer grammars_destroy(grammars)
    if lang != "" {
        if _, found := grammar_find(grammars, lang); !found {
            fmt.printfln("%s: unknown language", lang)
            return
        }
        print_health_row(dir, lang)
        return
    }
    fmt.println("grammars:", dir)
    if len(grammars) == 0 {
        fmt.println("  (no language registry — run download-deps.sh to generate `languages`)")
    }
    for g in grammars {
        print_health_row(dir, g.name)
    }
}

@(private = "file")
print_health_row :: proc(dir, lang: string) {
    mark := grammar_present(dir, lang) ? "✓ installed    " : "✗ not installed"
    fmt.printfln("  %s  %s", mark, lang)
}
